services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=fastfood'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017'
    networks:
      - 'red_mongo'
    volumes:
      - './data:/data/db'
  compass:
    image: 'haohanyang/compass-web'
    environment:
      - 'CW_MONGO_URI=mongodb://root:secret@mongodb:27017?authSource=admin'
    depends_on:
      - 'mongodb'
    ports:
      - '8081:8080'
    networks:
      - 'red_mongo'

networks:
  red_mongo:
    driver: bridge
